### ISSUE TITLE
Input doesn't support accent mark

### ISSUE THREAD

**Issue by Martoxdlol** [frencojobs/interact#13]
In languages like Spanish, characters with accent mark (for example, á é í ó ú) are ignored.
Also, pasting it from outside does the same.

For example:
```dart
final givenName = Input(prompt: 'Nombre').interact();
```

I use "Tomás" as input but i see this:

```
? Nombre › Toms
```

**Comment by Martoxdlol** [comment]
It seems to be a problem with dart platform itself. Not a problem with

**Comment by tratteo** [comment]
Any updates on this?

**Comment by Martoxdlol** [comment]
I did something research and it seems to be a problem with dart itself. The input methods provided bi IO package doesn't work either.

**Comment by tratteo** [comment]
Opening an issue on their side
https://github.com/dart-lang/tools/issues/1253

### Edit
Opened on the wrong repo.
The correct issue is now on the actual Dart SDK: https://github.com/dart-lang/sdk/issues/52788

**Comment by tratteo** [comment]
@frencojobs I got these answer from the issue I opened on the Dart SDK repo: https://github.com/dart-lang/sdk/issues/52788#issuecomment-1613614562

Would it be possible to fix the problem by implementing the suggestions? 
Thanks, sorry for tagging

**Comment by Martoxdlol** [comment]
> @frencojobs I got these answer from the issue I opened on the Dart SDK repo: [dart-lang/sdk#52788 (comment)](https://github.com/dart-lang/sdk/issues/52788#issuecomment-1613614562)
> 
> Would it be possible to fix the problem by implementing the suggestions? Thanks, sorry for tagging

It is still not working.
![Demo on Windows and Linux](https://github.com/frencojobs/interact/assets/35405382/c49078ef-2485-4b1f-a921-8be05bc8569a)

On Linux it works as expected but not on Windows

**Comment by cbarlow26** [comment]
@Martoxdlol @tratteo I know this is an old issue, but maybe [Interact2](https://pub.dev/packages/interact2) fixes the issues you're experiencing.

**Comment by Martoxdlol** [comment]
> @Martoxdlol @tratteo I know this is an old issue, but maybe [Interact2](https://pub.dev/packages/interact2) fixes the issues you're experiencing.

I will check it out! Thanks
