### ISSUE TITLE
Add a way to re-show the cursor

### ISSUE THREAD

**Issue by GZGavinZhao** [frencojobs/interact#3]
When we use a spinner, a typical usage is to wrap it around some code:
```dart
final gift = Spinner(
  icon: '🏆',
  leftPrompt: (done) => '', // prompts are optional
  rightPrompt: (done) => done
      ? 'here is a trophy for being patient'
      : 'searching a thing for you',
).interact();

await fetchTheGift();

gift.done();
```
![not_terminated](https://user-images.githubusercontent.com/74938940/126921659-24157958-4a6d-44a6-9453-a35c2047abd5.png)

However, if an exception is thrown, even though the spinner is stopped, the cursor of the terminal disappears!
```dart
final candy = Spinner(
  icon: '🏆',
  leftPrompt: (done) => '', // prompts are optional
  rightPrompt: (done) => done
      ? 'here is a trophy for being patient'
      : 'searching a thing for you',
).interact();

throw Exception('Me no like candy!');

candy.done();
```
![terminated](https://user-images.githubusercontent.com/74938940/126921668-6a085f54-9e2a-4b99-80f2-2e00713d8cea.png)

After a few testing, I found that the cursor would disappear if you terminate almost any interactive component. Perhaps add a top-level function that will make hidden cursor reappear?

**Comment by DRSchlaubi** [comment]
Can confirm happens in my CLI as well

**Comment by frencojobs** [comment]
Interact v2.1 should have a `reset` function that lets you reset the terminal values to your default ones. Refer to this section https://github.com/frencojobs/interact#handling-exceptions.

Thanks for taking the time to open this issue.

**Comment by DRSchlaubi** [comment]
Great will try that later

**Comment by GZGavinZhao** [comment]
Thank you so much for your work! I tried it and can confirm that the `reset()` function works perfectly, but the Ctrl+C issue is not resolved. When you force quit a program, the cursor still disappears.

I think the way the Flutter team achieve this might be useful: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/logger.dart#L908

**Comment by DRSchlaubi** [comment]
as @GZGavinZhao said reset() helps resetting the cursot, but somehow interactions block sigints

```dart
  var sigints = 0;
  _sigIntListener = ProcessSignal.sigint.watch().listen((event) {
    print('sigint $sigints');
    if (sigints++ >= 1) {
      exit(1);
    } else {
      _close();
    }
  });
  ```

I currently have this code, which works fine if there is currently no interactable on screen (only tried Select and Input), but if there is it does not get called

**Comment by frencojobs** [comment]
Hi. Sorry, yes I forgot some of the components consume signals. So there's no way users can handle Ctrl+C manually. 

v2.1.1 made components that required user input (confirm, input, etc) handle Ctrl+C together with input. For non-input components like spinners & progress bars, I added SIGINT handlers. So, just switch to v2.1.1, no changes are needed, everything should be good :)

Thanks.
